[package]
name = "meme_factory"
version = "1.0.0"
authors = []
license = "Apache-2.0"

[addresses]
meme_factory = "_"

[dev-addresses]
meme_factory = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"
